---
# Развертывание приложения
- name: Configure app servers
  hosts: docker
  become: true

  vars:
    app_docker_image: vdaishi/otus-reddit
    app_docker_version: 1.0

  tasks:

    - name: Run app docker container
      docker_container:
        name: reddit
        image: "{{ app_docker_image }}:{{ app_docker_version }}"
        ports:
          - "9292:9292"
      tags: app
