global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vadim_shalimov'
