---
 # Установка докера

- name: Prepare app instance image
  hosts: all
  become: true
  vars:
    ubuntu_release: xenial
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      tags: install

    - name: Install packages required to install Docker from repository
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common ]
        state: "present"
      tags: install

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install

    - name: Add apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_release }} stable
        state: present
      tags: install

    - name: Update apt and install docker-ce python-dockerpty
      apt:
        update_cache: yes
        name: [docker-ce, python-dockerpty]
        state: latest
      tags: install
