version: '3.3'
services:
  comment_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
  post_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  post:
    image: ${USER_NAME}/post:${VERSION_POST:-latest}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
  comment:
    image: ${USER_NAME}/comment:${VERSION_COMMENT:-latest}
    networks:
      - back_net
      - front_net
  ui:
    image: ${USER_NAME}/ui:${VERSION_UI:-latest}
    ports:
      - ${PORT_PUMA:-9292}:${PORT_UI:-9292}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

volumes:
  comment_db:
  post_db:

networks:
  front_net:
  back_net:
