plugin: gcp_compute
projects:
  - docker-279821
zones:
  - "europe-west4-a"
groups:
  docker: "'docker' in name"
filters: []
auth_kind: serviceaccount
service_account_file: "./gcpkey.json"
hostnames:
  # Показываем имена инстансов вместо их IP
  - name
compose:
  # Переменные, которыми мы можем пользоваться для в переменных и плейбуках Ansible
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
